QBShared = QBShared or {}
QBShared.VehicleHashes = {}

QBShared.Vehicles = {
    --- Motorcycles
    ['bf400'] = {
        ['name'] = 'BF400',
        ['brand'] = 'Nagasaki',
        ['model'] = 'bf400',
        ['price'] = 22000,
        ['category'] = 'motorcycles',
        ['categoryLabel'] = 'Motorcycles',
        ['hash'] = `bf400`,
        ['shop'] = 'pdm',
        ['cost'] = 10000,
    },
    ['hakuchou'] = {
        ['name'] = 'Hakuchou',
        ['brand'] = 'Shitzu',
        ['model'] = 'hakuchou',
        ['price'] = 17000,
        ['category'] = 'motorcycles',
        ['categoryLabel'] = 'Motorcycles',
        ['hash'] = `hakuchou`,
        ['shop'] = 'pdm',
        ['cost'] = 10000,
    },
    ['nemesis'] = {
        ['name'] = 'Nemesis',
        ['brand'] = 'Principe',
        ['model'] = 'nemesis',
        ['price'] = 20000,
        ['category'] = 'motorcycles',
        ['categoryLabel'] = 'Motorcycles',
        ['hash'] = `nemesis`,
        ['shop'] = 'pdm',
        ['cost'] = 10000,
    },
        --- Military
    ['Barracks'] = {
        ['name'] = 'Barracks',
        ['brand'] = 'Annis',
        ['price'] = 9000,
        ['category'] = 'military',
        ['categoryLabel'] = 'military',
        ['model'] = 'barracks',
        ['hash'] = `barracks`,
        ['shop'] = 'pdm',
        ['cost'] = 10000,
    },
    ['Rhino'] = {
        ['name'] = 'Rhino',
        ['brand'] = 'Annis',
        ['price'] = 15500,
        ['category'] = 'military',
        ['categoryLabel'] = 'Off Road',
        ['model'] = 'rhino',
        ['hash'] = `rhino`,
        ['shop'] = 'pdm',
        ['cost'] = 10000,
    },
    ['Halftrack'] = {
        ['name'] = 'halftrack',
        ['brand'] = 'Annis',
        ['price'] = 7500,
        ['category'] = 'military',
        ['categoryLabel'] = 'Off Road',
        ['model'] = 'halftrack',
        ['hash'] = `halftrack`,
        ['shop'] = 'pdm',
        ['cost'] = 10000,
    },
    ['technical3'] = {
        ['name'] = 'technical3',
        ['brand'] = 'Annis',
        ['price'] = 15500,
        ['category'] = 'military',
        ['categoryLabel'] = 'Off Road',
        ['model'] = 'technical3',
        ['hash'] = `technical3`,
        ['shop'] = 'pdm',
        ['cost'] = 10000,
    },
    ['Barrage'] = {
        ['name'] = 'Barrage',
        ['brand'] = 'Annis',
        ['price'] = 7500,
        ['category'] = 'military',
        ['categoryLabel'] = 'Off Road',
        ['model'] = 'barrage',
        ['hash'] = `barrage`,
        ['shop'] = 'pdm',
        ['cost'] = 10000,
    },
    --- Off-Road
    ['blazer'] = {
        ['name'] = 'Blazer',
        ['brand'] = 'Annis',
        ['price'] = 7500,
        ['category'] = 'offroad',
        ['categoryLabel'] = 'Off Road',
        ['model'] = 'blazer',
        ['hash'] = `blazer`,
        ['shop'] = 'pdm',
        ['cost'] = 10000,
    },
    ['mesa3'] = {
        ['name'] = 'Mesa Merryweather',
        ['brand'] = 'Canis',
        ['model'] = 'mesa3',
        ['price'] = 400000,
        ['category'] = 'offroad',
        ['categoryLabel'] = 'Off Road',
        ['hash'] = `mesa3`,
        ['shop'] = 'pdm',
        ['cost'] = 10000,
    },
    ['winky'] = {
        ['name'] = 'Winky',
        ['brand'] = 'Vapid',
        ['price'] = 10000,
        ['category'] = 'military',
        ['categoryLabel'] = 'Military',
        ['model'] = 'winky',
        ['hash'] = `winky`,
        ['shop'] = 'pdm',
        ['cost'] = 10000,
    },
    ['seashark3'] = {
        ['name'] = 'Seashark Yacht',
        ['brand'] = 'Speedophile',
        ['model'] = 'seashark3',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `seashark3`,
        ['shop'] = 'pdm',
        ['cost'] = 10000,
    },
    ['dinghy'] = {
        ['name'] = 'Dinghy 2-Seater',
        ['brand'] = 'Nagasaki',
        ['model'] = 'dinghy',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `dinghy`,
        ['shop'] = 'pdm',
        ['cost'] = 10000,
    },
    ['suntrap'] = {
        ['name'] = 'Suntrap',
        ['brand'] = 'Shitzu',
        ['model'] = 'suntrap',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `suntrap`,
        ['shop'] = 'pdm',
        ['cost'] = 10000,
    },
    ['cargobob'] = {
        ['name'] = 'Frogger (Trevor Philips Enterprises)',
        ['brand'] = 'Unknown',
        ['model'] = 'cargobob',
        ['price'] = 52000,
        ['category'] = 'helicopters',
        ['categoryLabel'] = 'Helicopters',
        ['hash'] = `cargobob`,
        ['shop'] = 'pdm',
        ['cost'] = 10000,
    },
    -- ['maverick'] = {
    --     ['name'] = 'Maverick',
    --     ['brand'] = 'Unknown',
    --     ['model'] = 'maverick',
    --     ['price'] = 52000,
    --     ['category'] = 'helicopters',
    --     ['categoryLabel'] = 'Helicopters',
    --     ['hash'] = `maverick`,
    --     ['shop'] = 'air',
    -- },
    ['supervolito'] = {
        ['name'] = 'SuperVolito',
        ['brand'] = 'Buckingham',
        ['model'] = 'supervolito',
        ['price'] = 52000,
        ['category'] = 'helicopters',
        ['categoryLabel'] = 'Helicopters',
        ['hash'] = `supervolito`,
        ['shop'] = 'pdm',
        ['cost'] = 10000,
    },
    ['Lazer'] = {
        ['name'] = 'Lazer',
        ['brand'] = 'Buckingham',
        ['model'] = 'LAZER',
        ['price'] = 45000,
        ['category'] = 'planes',
        ['categoryLabel'] = 'Planes',
        ['hash'] = `LAZER`,
        ['shop'] = 'pdm',
        ['cost'] = 10000,
    },
    ['nimbus'] = {
        ['name'] = 'Nimbus',
        ['brand'] = 'Buckingham',
        ['model'] = 'nimbus',
        ['price'] = 45000,
        ['category'] = 'planes',
        ['categoryLabel'] = 'Planes',
        ['hash'] = `nimbus`,
        ['shop'] = 'pdm',
        ['cost'] = 10000,
    },
    ['conada'] = {
        ['name'] = 'Conada',
        ['brand'] = 'Buckingham',
        ['model'] = 'conada',
        ['price'] = 115000,
        ['category'] = 'helicopters',
        ['categoryLabel'] = 'Helicopters',
        ['hash'] = `conada`,
        ['shop'] = 'pdm',
        ['cost'] = 10000,
    },
}

for _, v in pairs(QBShared.Vehicles) do
    QBShared.VehicleHashes[v.hash] = v
end
